language: node_js
node_js:
- node
- '14'
- '12'
- '11'
sudo: false
git:
  submodules: false
services:
- mongodb
before_script:
- npm install
script:
- npm run test
env:
  global:
    secure: fe4oofZn2hYBjM9t4zrV6mXdQwSmVos7hb7+LpVwfM3/pE6ZGr4vsa3Vc0yAwxKi1aIqqw7vyWPLVGMUK0N8S9FmtcS9vjMGOfYeWKVbWIGN+/K81rj91s7ik8DAjgkdkSezSA28rIzsrXuO/40Y41G7t10VZnaqiCsGVXhYs08Qf3DnSq6LebQdppnZIl24gat9LVqvcrLNqRSwrLVX68qxlXIGFUgH8Msod56+XV4efgW8SbOZFQi6l9iszpd+yQGbte1sj/tjohw/0egBW4HLXNCLzy4KksQTnUuWf5eAC65Znn1YD0IdNDgLZuZzO6pAd3xsPYjhrrIl8sQi5yJUen1sBFlLocwspAGrSeMxwanOOK+iNtWGlu8xnN/HvVKVxPC9ivyH8xYpX8PvT6iWAnZL42aQfLE8fE+uKeR+JaTkV02C088Kxfa3ZzC+8ujKbkeIu0J8U3fewRVJm5d8XCRZmmup2pmIiJwg2nydmv4W342TH6evqrx2P3+bsoFEB44p/8dIWG4LpP3Q9G7VWoNxGkD8tVmXNZsfQJb6/xXsvANH0W+QQF/myKneB8gKkt2h6xVxR7PHXCTpYvPT8FaUElmA0TLHM7JkTJ5K3U3rSfA6nYXBQHaOABofKmw36DH1OiGyIJaP7Wf1IWDRvt5IbhCI6rS7DnQdnyM=
