language: node_js

node_js:
    - "node"
    - "14"
    - "12"
    - "11"

services: mongodb

sudo: false

git:
    submodules: false

before_install:
- openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in config.json.enc -out config.json -d

before_script:
    - npm install

script:
    - npm test