language: node_js

node_js:
    - "node"
    - "14"
    - "12"
    - "11"

services: mongodb

sudo: false

git:
    submodules: false

before_install:
- cp .ignored.file.copy config.json

before_script:
    - npm install

script:
    - npm test